/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv1AmbulanceWlList {
    }
}
declare global {
    interface HTMLCv1AmbulanceWlListElement extends Components.Cv1AmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv1AmbulanceWlListElement: {
        prototype: HTMLCv1AmbulanceWlListElement;
        new (): HTMLCv1AmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv1-ambulance-wl-list": HTMLCv1AmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv1AmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv1-ambulance-wl-list": Cv1AmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv1-ambulance-wl-list": LocalJSX.IntrinsicElements["cv1-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLCv1AmbulanceWlListElement>;
        }
    }
}
